# Generated by Django 4.2.1 on 2023-06-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0002_alter_korisnik_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upisi',
            name='status',
            field=models.CharField(choices=[('up', 'upisan'), ('pass', 'polozen'), ('fail', 'izgubio potpis')], default='up', max_length=50),
        ),
    ]
