# Generated by Django 4.2.1 on 2023-06-10 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0004_alter_upisi_predmet_id_alter_upisi_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmeti',
            name='nositelj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
